= Toy Moderation README
Ilari Ahtiainen <ilari at ahtiainen dot eu>
:description: Documentation of the small task given to me
:sectanchors:

This repository contains a small demonstration application. It has two services, nginx as a frontend and flask application as a backend services.
The purpose is that docker containers are put as a PODs into a Kubernetes cluster and the service (nginx) is available from outside and backend is accessible by frontend application only.

== Prerequisites
:icons: font

Due to the nature of the task given, it is assumed that there is a Linux environment in use. MacOS or Windows environments are not supported, however it should not be too hard to convert these into the MacOS or Windows environments.
There is a assumptions made that one have installed and/or available the following software stacks and needed modules: 

* docker binaries installed for creating docker images
* kubernetes cluster available
* way to set the created images available for the kubernetes cluster

For quick image creation one can use the create script provided in the resources directory by
[source, bash]
cd resources
bash create.bash    

The above script creates two docker images to the local environment with tags 

* ghcr.io/iuaui71/backend:latest
* ghcr.io/iuaui71/frontend:latest

IMPORTANT: You need to use the above tags or alter the tags accordingly in your Kubernetes related yaml files!

== Deploying into the Kubernetes environment

Please see the README in the kubernetes directory

== The information about How it all works

You can inspect and try to understand how this implementation works.
Short description, however, is as follows

* we create a python application to handle 'api requests'
** we do it with TDD style (test driven development)
* we create a nginx environment to host a static 'comment site'
* we create docker images both of the service parts
* we create a kubernetes environment with 
** docker images
*** we need a secret to pull the images from the registry if they are to be pulled from there
** service for the backend to be accessible by frontend
** service for the frontend to be accessible by "world"

What to do with the app?

* in the front page there is comment field. Please put some comment on it. (You can even try if there is any XSS vulnerabilities available)
* click "submit"

Current images in the github container registry (ghcr.io) are created with the Docker and resource files included in this repository.
I hope that you are able to create, test and run the container in your Kubernetes environment.