apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: toymoderation
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
      - name: toymoderation 
      containers:
      - image: ghcr.io/iuaui71/backend:latest
        name: backend
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        resources: {}
status: {}
